services:
  frontend:
    container_name: trelloia-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3030:3030'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - trelloia-shared

networks:
  trelloia-shared:
    external: true
