services:
  frontend:
    container_name: trelloia-frontend
    build:
      context: .
    ports:
      - '3002:3002'
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/.next
    working_dir: /app
    command: pnpm run dev
    restart: unless-stopped
    networks:
      - trelloia-shared

networks:
  trelloia-shared:
    external: true
