name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instala Node.js e configura cache para pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Instala pnpm manualmente (corrige erro de "pnpm não encontrado")
      - name: Install pnpm
        run: npm install -g pnpm@10.7.1

      # 4. Confirma versão instalada (debug opcional)
      - name: Check pnpm version
        run: pnpm -v

      # 5. Instala dependências com lockfile travado
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 6. Valida formatação com Prettier
      - name: Check code formatting (Prettier)
        run: pnpm exec prettier --check .

      # 7. Roda testes (Jest)
      - name: Run tests
        run: pnpm test

      # 8. Build do projeto
      - name: Build Next.js application
        run: pnpm run build

      # 9. Deploy na Vercel apenas no push da main
      - name: Deploy to Vercel
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          github-comment: false